default:
  image: python:3.10.5-slim
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - dir
    - python -m pip install -r requirements.txt


migrations:
  stage: build
  script:
    - cd mainapp
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py check

django-tests:
  stage: test
  script:
    - python mainapp/manage.py test test_urls
