version: '3'
services:
  database:
    image: postgres
#    command: CREATE DATABASE authenticationapp
    environment:
      POSTGRES_DB: authenticationapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - app
    volumes:
      - ./data/db:/var/lib/postgresql/data
  django_app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    links:
      - database
    networks:
      - app
    depends_on:
      - database

networks:
  app: